"""Misalignment transform parity and the semantics that ride on it."""

import at
import numpy as np
import pytest

from lume_pyat.solve import solve_orbit
from lume_pyat.tests.conftest import build_test_ring
from lume_pyat.utils import apply_misalignment

# Reference T1/T2/R1/R2, generated by running the pySC-ported implementation
# this module was moved from against the same inputs. Parity is what makes the
# move safe: the transform is a port of pySC's update_transformation, so these
# numbers are the contract, not an implementation detail. Tolerances are tight
# enough to catch any formula change while tolerating last-ulp BLAS
# differences across platforms (np.linalg.inv is involved).
REFERENCE = {
    "quad_dx": {
        "element": ("quad", 0.3, 0.0),
        "kwargs": {"dx": 0.0003},
        "T1": [-0.0003, 0.0, 0.0, 0.0, 0.0, 0.0],
        "T2": [0.0003, 0.0, 0.0, 0.0, 0.0, 0.0],
        "R1": [
            [1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
            [-0.0, -0.0, 1.0, 0.0, 0.0, 0.0],
            [0.0, -0.0, 0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, 0.0, 0.0, 0.0, 1.0],
        ],
        "R2": [
            [1.0, 0.0, -0.0, -0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
            [-0.0, -0.0, 1.0, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, -0.0, -0.0, 0.0, 1.0],
        ],
    },
    "quad_dx_dy_roll": {
        "element": ("quad", 0.3, 0.0),
        "kwargs": {"dx": 0.0002, "dy": 0.00015, "roll": 0.02},
        "T1": [-0.00019999999999999998, 0.0, -0.00015000000000000001, 0.0, 0.0, 0.0],
        "T2": [0.0002, 0.0, 0.00015, 0.0, 0.0, 0.0],
        "R1": [
            [0.9998000066665778, 0.0, 0.01999866669333308, 0.0, 0.0, 0.0],
            [0.0, 0.9998000066665778, 0.0, 0.01999866669333308, 0.0, 0.0],
            [-0.01999866669333308, -0.0, 0.9998000066665778, 0.0, 0.0, 0.0],
            [0.0, -0.01999866669333308, 0.0, 0.9998000066665778, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, 0.0, 0.0, 0.0, 1.0],
        ],
        "R2": [
            [0.9998000066665778, 0.0, -0.01999866669333308, -0.0, 0.0, 0.0],
            [0.0, 0.9998000066665778, 0.0, -0.01999866669333308, 0.0, 0.0],
            [0.01999866669333308, 0.0, 0.9998000066665778, 0.0, 0.0, 0.0],
            [0.0, 0.01999866669333308, 0.0, 0.9998000066665778, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, -0.0, -0.0, 0.0, 1.0],
        ],
    },
    "bend_dx_roll": {
        "element": ("bend", 1.0, 0.7853981633974483),
        "kwargs": {"dx": 0.0001, "roll": 0.001},
        "T1": [-0.0001, 0.0, 3.132150363843339e-24, 0.0, 0.0, 0.0],
        "T2": [
            7.08425440902121e-05,
            2.499999791526051e-07,
            -0.00037297325965916203,
            -0.0007071066633354231,
            0.0,
            7.084254409021209e-05,
        ],
        "R1": [
            [0.9999995000000417, 0.0, 0.0009999998333333417, 0.0, 0.0, 0.0],
            [0.0, 0.9999995000000417, 0.0, 0.0009999998333333417, 0.0, 0.0],
            [-0.0009999998333333417, -0.0, 0.9999995000000417, 0.0, 0.0, 0.0],
            [0.0, -0.0009999998333333417, 0.0, 0.9999995000000417, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, 0.0, 0.0, 0.0, 1.0],
        ],
        "R2": [
            [
                0.9999997499999583,
                7.084252637957313e-05,
                -0.0007071068401121185,
                -5.009324749713331e-08,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.9999997500000208,
                0.0,
                -0.0007071066633354233,
                2.499999791526051e-07,
                0.0,
            ],
            [
                0.0007071068401121185,
                5.009324749713331e-08,
                1.0,
                7.084254409021209e-05,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.0007071066633354233,
                0.0,
                0.9999995000000417,
                -0.0007071066633354231,
                0.0,
            ],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [
                -2.500000416526103e-07,
                -1.7710638973329904e-11,
                -0.0007071068401121184,
                -5.0093247497133305e-08,
                0.0,
                1.0,
            ],
        ],
    },
    "bend_roll_only": {
        "element": ("bend", 1.0, 0.7853981633974483),
        "kwargs": {"roll": -0.001},
        "T1": [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
        "T2": [
            1.3184829388487484e-07,
            2.499999791526051e-07,
            0.00037292325965499536,
            0.0007071066633354231,
            0.0,
            1.3184829388487484e-07,
        ],
        "R1": [
            [0.9999995000000417, 0.0, -0.0009999998333333417, -0.0, 0.0, 0.0],
            [0.0, 0.9999995000000417, 0.0, -0.0009999998333333417, -0.0, 0.0],
            [0.0009999998333333417, 0.0, 0.9999995000000417, 0.0, 0.0, 0.0],
            [0.0, 0.0009999998333333417, 0.0, 0.9999995000000417, 0.0, 0.0],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [-0.0, -0.0, 0.0, 0.0, 0.0, 1.0],
        ],
        "R2": [
            [
                0.9999997499999583,
                1.3184826092279588e-07,
                0.0007071068401121185,
                9.323083046310782e-11,
                0.0,
                0.0,
            ],
            [
                0.0,
                0.9999997500000208,
                0.0,
                0.0007071066633354233,
                2.499999791526051e-07,
                0.0,
            ],
            [
                -0.0007071068401121185,
                -9.323083046310782e-11,
                1.0,
                1.3184829388487484e-07,
                0.0,
                0.0,
            ],
            [
                0.0,
                -0.0007071066633354233,
                0.0,
                0.9999995000000417,
                0.0007071066633354231,
                0.0,
            ],
            [0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
            [
                -2.500000416526103e-07,
                -3.296207896304431e-14,
                0.0007071068401121184,
                9.32308304631078e-11,
                0.0,
                1.0,
            ],
        ],
    },
}


def build_element(kind: str, length: float, angle: float):
    if kind == "quad":
        return at.Quadrupole("Q", length, 1.0)
    return at.Dipole("B", length, angle)


@pytest.mark.parametrize("case", sorted(REFERENCE))
@pytest.mark.parametrize("attribute", ["T1", "T2", "R1", "R2"])
def test_transform_matches_the_reference_implementation(case, attribute):
    spec = REFERENCE[case]
    element = build_element(*spec["element"])

    apply_misalignment(element, **spec["kwargs"])

    np.testing.assert_allclose(
        getattr(element, attribute),
        np.array(spec[attribute]),
        rtol=1e-12,
        atol=1e-18,
    )


def test_a_straight_element_exit_transform_mirrors_the_entrance():
    element = at.Quadrupole("Q", 0.3, 1.0)
    apply_misalignment(element, dx=200e-6, dy=150e-6, roll=0.02)

    np.testing.assert_allclose(
        element.T2, -np.asarray(element.T1), rtol=1e-12, atol=1e-18
    )


def test_a_bend_uses_its_own_curvature():
    # The exit transform is bend-aware, so identical offsets on a straight and
    # a bending element must not produce the same T2.
    straight = at.Quadrupole("Q", 1.0, 1.0)
    bending = at.Dipole("B", 1.0, 2 * np.pi / 8)
    for element in (straight, bending):
        apply_misalignment(element, dx=100e-6, roll=0.001)

    assert not np.allclose(straight.T2, bending.T2, rtol=1e-6, atol=1e-12)


def test_geometry_attributes_default_to_zero_when_absent():
    # Length/BendingAngle are read defensively; an element carrying neither
    # must behave as a zero-length straight one.
    class Bare:
        pass

    bare, straight = Bare(), at.Marker("M")
    apply_misalignment(bare, dx=100e-6, roll=0.001)
    apply_misalignment(straight, dx=100e-6, roll=0.001)

    np.testing.assert_allclose(bare.T1, straight.T1, rtol=1e-12, atol=1e-18)
    np.testing.assert_allclose(bare.T2, straight.T2, rtol=1e-12, atol=1e-18)


def test_zero_misalignment_leaves_the_orbit_untouched(test_ring):
    index = test_ring.get_uint32_index("QUAD_F_01")[0]
    apply_misalignment(test_ring[index], dx=0.0, dy=0.0, roll=0.0)

    assert np.abs(solve_orbit(test_ring)).max() == pytest.approx(0.0, abs=1e-12)


def test_dx_on_a_quadrupole_shifts_the_horizontal_plane_only(test_ring):
    index = test_ring.get_uint32_index("QUAD_F_01")[0]
    apply_misalignment(test_ring[index], dx=300e-6)

    orbit = solve_orbit(test_ring)
    assert np.abs(orbit[:, 0]).max() > 1e-5
    # No x-y coupling without roll.
    assert np.abs(orbit[:, 2]).max() == pytest.approx(0.0, abs=1e-12)


def test_the_transform_is_absolute_not_additive(test_ring):
    index = test_ring.get_uint32_index("QUAD_F_01")[0]
    element = test_ring[index]

    apply_misalignment(element, dx=300e-6, dy=200e-6)
    combined = np.array(element.T1)

    apply_misalignment(element, dy=200e-6)
    dy_only = np.array(element.T1)

    apply_misalignment(element, dx=300e-6)
    apply_misalignment(element, dy=200e-6)
    sequential = np.array(element.T1)

    # The second call replaced the first outright rather than composing with
    # it, so the sequence lands on dy alone -- not on dx and dy together.
    np.testing.assert_allclose(sequential, dy_only, rtol=1e-12, atol=1e-18)
    assert not np.allclose(sequential, combined, rtol=1e-9, atol=1e-15)


def test_reverting_to_zero_restores_the_baseline_orbit(test_ring):
    baseline = solve_orbit(test_ring)
    index = test_ring.get_uint32_index("QUAD_F_01")[0]

    apply_misalignment(test_ring[index], dx=200e-6, dy=150e-6, roll=0.02)
    assert np.abs(solve_orbit(test_ring)).max() > 1e-6

    apply_misalignment(test_ring[index], dx=0.0, dy=0.0, roll=0.0)
    np.testing.assert_allclose(solve_orbit(test_ring), baseline, rtol=0, atol=1e-12)


def test_roll_on_a_bend_couples_horizontal_offset_into_the_vertical_plane():
    def rolled_orbit(roll):
        ring = build_test_ring()
        index = ring.get_uint32_index("BEND_01")[0]
        apply_misalignment(ring[index], dx=100e-6, roll=roll)
        return solve_orbit(ring)

    unrolled = rolled_orbit(0.0)
    positive = rolled_orbit(1e-3)
    negative = rolled_orbit(-1e-3)

    assert np.abs(unrolled[:, 2]).max() == pytest.approx(0.0, abs=1e-12)
    assert np.abs(positive[:, 2]).max() > 1e-4

    # Sign convention: the induced vertical orbit is odd in roll. This is what
    # pins the exit transform's roll sign rather than the opposite one.
    np.testing.assert_allclose(positive[:, 2], -negative[:, 2], rtol=0, atol=1e-9)
